name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this if your branch is `main`

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .  # Deploys the root directory (adjust if needed)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
